// VIGIL-OR Surgical Intelligence Data Store
// Realistic Clinical Datasets for OR-01 Command Center

export const patients = [
  {
    id: "P001",
    name: "Test Patient",
    alternateName: "Arun Kumar",
    age: 45,
    gender: "Male",
    bloodGroup: "O+",
    height: "178 cm",
    weight: "76 kg",
    bmi: "24.0",
    room: "OR-01",
    procedure: "Laparoscopic Appendectomy",
    procedureCategory: "General Surgery",
    surgicalStatus: "IN PROGRESS",
    anesthesia: "General Endotracheal",
    leadSurgeon: "Dr. A. Vance, MD, FACS",
    anesthesiologist: "Dr. K. Chen, MD",
    scrubNurse: "S. Miller, RN, CNOR",
    circulatingNurse: "J. Ramos, RN",
    admissionDate: "2026-09-01",
    startTime: "07:30 AM",
    estimatedDuration: "60 mins",
    elapsedTime: "00:42:18",
    allergies: ["Penicillin (Mild Rash)", "Latex (None Reported)"],
    preOpDiagnosis: "Acute suppurative appendicitis with localized peritonitis",
    postOpPlan: "Recovery in PACU -> Surgical Ward 4B -> Liquid diet post-6h",
    vitals: {
      heartRate: 72,
      spo2: 98,
      bpSystolic: 120,
      bpDiastolic: 80,
      bp: "120/80",
      map: 93, // Mean Arterial Pressure
      respiratoryRate: 16,
      temperature: 36.8,
      etco2: 38, // End-tidal CO2
      perfusionIndex: 4.2,
      cardiacRhythm: "Sinus Rhythm (Normal)",
      ecgLead: "Lead II",
      monitorStatus: "CONNECTED",
    },
    clinicalSummary:
      "Patient is a 45-year-old male presenting with acute right lower quadrant abdominal pain, McBurney's point tenderness, and mild leukocytosis. Laparoscopic appendectomy underway. Hemodynamics remain stable under Sevoflurane/Fentanyl balanced general anesthesia. Vital signs are within target limits with good oxygenation.",
    recentAlerts: [
      { id: "a1", type: "info", text: "Cephazolin 2g IV administered at 07:15 (T-15m prior to incision)", time: "07:15" },
      { id: "a2", type: "info", text: "Pneumoperitoneum established at 12 mmHg CO2", time: "07:38" },
      { id: "a3", type: "warning", text: "Checklist Time-Out verified by all surgical team members", time: "07:35" },
    ],
  },
  {
    id: "P002",
    name: "Elena Rostova",
    alternateName: "Priya Sharma",
    age: 42,
    gender: "Female",
    bloodGroup: "A+",
    height: "165 cm",
    weight: "62 kg",
    bmi: "22.8",
    room: "OR-02",
    procedure: "Left Craniotomy (Subdural Evacuation)",
    procedureCategory: "Neurosurgery",
    surgicalStatus: "PRE-OPERATIVE",
    anesthesia: "General (Neuro-protective)",
    leadSurgeon: "Dr. N. Sterling, MD, FAANS",
    anesthesiologist: "Dr. M. Zhao, MD",
    scrubNurse: "T. Larson, RN",
    circulatingNurse: "D. Washington, RN",
    admissionDate: "2026-09-01",
    startTime: "09:00 AM",
    estimatedDuration: "120 mins",
    elapsedTime: "00:00:00",
    allergies: ["Sulfa Drugs (Anaphylaxis)", "NSAIDs"],
    preOpDiagnosis: "Subacute left hemispheric subdural hematoma with 4mm midline shift",
    postOpPlan: "Immediate transfer to Neuro-ICU -> Hourly Glasgow Coma Scale -> Follow-up non-contrast CT in 6h",
    vitals: {
      heartRate: 68,
      spo2: 99,
      bpSystolic: 130,
      bpDiastolic: 82,
      bp: "130/82",
      map: 98,
      respiratoryRate: 14,
      temperature: 36.6,
      etco2: 35,
      perfusionIndex: 3.8,
      cardiacRhythm: "Sinus Bradycardia (Stable)",
      ecgLead: "Lead II",
      monitorStatus: "STANDBY",
    },
    clinicalSummary:
      "42-year-old female with persistent progressive headaches and mild right-sided pronator drift following trauma 10 days prior. MRI & CT scans confirm left convex subdural collection. Pre-anesthetic evaluation complete. Cross-matched blood 2 units PRBC available.",
    recentAlerts: [
      { id: "b1", type: "warning", text: "Mannitol 20% 100ml IV prepared for ICP management", time: "08:10" },
      { id: "b2", type: "info", text: "Pre-op non-contrast head CT uploaded to PACS viewer", time: "08:25" },
    ],
  },
  {
    id: "P003",
    name: "David Kim",
    alternateName: "Rahul Menon",
    age: 61,
    gender: "Male",
    bloodGroup: "B+",
    height: "172 cm",
    weight: "84 kg",
    bmi: "28.4",
    room: "OR-03",
    procedure: "Coronary Artery Bypass Graft (CABG x3)",
    procedureCategory: "Cardiothoracic",
    surgicalStatus: "SCHEDULED",
    anesthesia: "High-dose Narcotic / Isoflurane",
    leadSurgeon: "Dr. H. Rossi, MD, FACS",
    anesthesiologist: "Dr. P. Dubois, MD",
    scrubNurse: "K. Novak, RN",
    circulatingNurse: "A. Patel, RN",
    admissionDate: "2026-09-01",
    startTime: "11:30 AM",
    estimatedDuration: "240 mins",
    elapsedTime: "00:00:00",
    allergies: ["No Known Drug Allergies (NKDA)"],
    preOpDiagnosis: "Triple vessel coronary artery disease (LAD 90%, RCA 85%, LCx 80%)",
    postOpPlan: "Transfer to Cardiac Surgical ICU intubated -> Continuous Swan-Ganz monitoring -> Arterial line",
    vitals: {
      heartRate: 84,
      spo2: 97,
      bpSystolic: 138,
      bpDiastolic: 86,
      bp: "138/86",
      map: 103,
      respiratoryRate: 18,
      temperature: 37.0,
      etco2: 37,
      perfusionIndex: 3.1,
      cardiacRhythm: "Sinus Rhythm with Occasional PACs",
      ecgLead: "Lead II + V5",
      monitorStatus: "READY",
    },
    clinicalSummary:
      "61-year-old male with unstable angina refractory to medical therapy. Coronary angiography reveals severe triple-vessel stenosis. Left ventricular ejection fraction preserved at 52%. Cardiopulmonary bypass priming initiated.",
    recentAlerts: [
      { id: "c1", type: "info", text: "Transesophageal echocardiography (TEE) probe calibrated", time: "10:45" },
      { id: "c2", type: "info", text: "Heparin 300 IU/kg dose verified with perfusionist", time: "11:00" },
    ],
  },
];

export const medicalReports = [
  {
    id: "REP-MRI-01",
    patientId: "P001",
    patientName: "Test Patient (Arun Kumar)",
    type: "MRI",
    title: "Abdominal / Pelvic MRI Contrast Study",
    date: "2026-09-01",
    modality: "MRI 3.0 Tesla (T1/T2/DWI)",
    slicesTotal: 32,
    currentSlice: 16,
    radiologist: "Dr. V. Gupta, MD, Radiologist",
    findings:
      "1. Visualized appendix is dilated measuring 9.8 mm in outer diameter with mural hyperenhancement and localized periappendiceal fat stranding.\n2. No appendicolith or signs of frank perforation or organized abscess cavity.\n3. Liver, kidneys, and spleen unremarkable.\n4. Minimal free fluid in the rectovesical pouch.",
    conclusion: "Findings consistent with acute uncomplicated appendicitis. Surgical excision recommended.",
    imageUrl: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80",
    imageType: "mri",
  },
  {
    id: "REP-CT-01",
    patientId: "P001",
    patientName: "Test Patient (Arun Kumar)",
    type: "CT",
    title: "Contrast-Enhanced Abdominopelvic CT Scan",
    date: "2026-08-31",
    modality: "128-Slice MDCT (0.5mm Reconstruct)",
    slicesTotal: 48,
    currentSlice: 24,
    radiologist: "Dr. S. Thornton, MD, Radiologist",
    findings:
      "1. Appendix is prominently distended (10mm) in the retrocecal position with hyperemic wall thickening.\n2. Surrounding mesenteric haziness noted in the right iliac fossa.\n3. No pneumoperitoneum or extraluminal gas bubbles to suggest micro-perforation.\n4. Visualized bowel loops show normal caliber without obstruction.",
    conclusion: "Acute retrocecal appendicitis with early periappendiceal inflammatory changes.",
    imageUrl: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=1200&q=80",
    imageType: "ct",
  },
  {
    id: "REP-LAB-01",
    patientId: "P001",
    patientName: "Test Patient (Arun Kumar)",
    type: "LABS",
    title: "Pre-Operative Comprehensive Metabolic & CBC Panel",
    date: "2026-09-01",
    modality: "Hematology & Clinical Biochemistry",
    slicesTotal: 1,
    currentSlice: 1,
    radiologist: "Central Pathology Lab",
    findings:
      "• Hemoglobin: 14.8 g/dL (Normal: 13.5 - 17.5)\n• White Blood Cells (WBC): 13,800 /uL [HIGH] (Normal: 4,500 - 11,000)\n• Neutrophils: 82% [HIGH] (Normal: 40 - 70%)\n• Platelets: 245,000 /uL (Normal: 150,000 - 400,000)\n• Serum Sodium: 139 mEq/L (Normal: 135 - 145)\n• Serum Potassium: 4.1 mEq/L (Normal: 3.5 - 5.0)\n• Serum Creatinine: 0.9 mg/dL (Normal: 0.7 - 1.3)\n• PT / INR: 11.2s / 1.02 (Normal Coagulation Profile)",
    conclusion: "Moderate leukocytosis with neutrophilic left shift secondary to acute inflammation. Renal and coagulation parameters within safe surgical limits.",
    imageUrl: "",
    imageType: "lab",
  },
  {
    id: "REP-ECG-01",
    patientId: "P001",
    patientName: "Test Patient (Arun Kumar)",
    type: "OTHER",
    title: "12-Lead Diagnostic Electrocardiogram",
    date: "2026-09-01",
    modality: "Standard 12-Lead ECG @ 25mm/s, 10mm/mV",
    slicesTotal: 1,
    currentSlice: 1,
    radiologist: "Dr. J. Palmer, FACC",
    findings:
      "• Heart Rate: 72 BPM\n• PR Interval: 156 ms\n• QRS Duration: 88 ms\n• QT/QTc: 388 / 418 ms\n• Axis: Normal (45 degrees)\n• Rhythm: Regular Sinus Rhythm\n• ST Segment: Isoelectric across all precordial and limb leads\n• T Waves: Normal morphology",
    conclusion: "Normal 12-lead ECG. No ischemic changes or conduction delays detected.",
    imageUrl: "",
    imageType: "ecg",
  },
];

export const surgicalChecklistData = [
  {
    category: "SIGN IN",
    phase: "Before induction of anesthesia",
    phaseDescription: "With at least nurse and anesthesia professional",
    items: [
      { id: "c1", label: "Patient identity, site, procedure, and consent confirmed", checked: true, required: true },
      { id: "c2", label: "Surgical site marked / not applicable", checked: true, required: true },
      { id: "c3", label: "Anesthesia safety check completed (machine, medications, monitor)", checked: true, required: true },
      { id: "c4", label: "Pulse oximeter on patient and functioning", checked: true, required: true },
      { id: "c5", label: "Does patient have known allergy? (Penicillin verified & flagged)", checked: true, required: true },
      { id: "c6", label: "Difficult airway or aspiration risk assessed & equipment ready", checked: true, required: false },
      { id: "c7", label: "Risk of >500ml blood loss assessed & adequate IV access verified", checked: true, required: false },
    ],
  },
  {
    category: "TIME OUT",
    phase: "Before skin incision",
    phaseDescription: "With nurse, anesthesia professional, and surgeon",
    items: [
      { id: "c8", label: "Confirm all team members introduced by name and role", checked: true, required: true },
      { id: "c9", label: "Surgeon, anesthesia, nurse verbally confirm patient, site, and procedure", checked: true, required: true },
      { id: "c10", label: "Antibiotic prophylaxis administered within 60 min before incision (Cephazolin 2g IV)", checked: true, required: true },
      { id: "c11", label: "Anticipated critical events: Surgeon reviews critical/unexpected steps, operative duration, blood loss", checked: true, required: true },
      { id: "c12", label: "Anticipated critical events: Anesthesia team reviews patient-specific concerns", checked: true, required: true },
      { id: "c13", label: "Anticipated critical events: Nursing team reviews sterility, equipment issues", checked: true, required: true },
      { id: "c14", label: "Essential imaging displayed and confirmed on OR monitors", checked: true, required: true },
      { id: "c15", label: "Laparoscopic insufflator pressure set to 12 mmHg", checked: true, required: false },
    ],
  },
  {
    category: "SIGN OUT",
    phase: "Before patient leaves operating room",
    phaseDescription: "With nurse, anesthesia professional, and surgeon",
    items: [
      { id: "c16", label: "Nurse verbally confirms: Name of the procedure recorded", checked: true, required: true },
      { id: "c17", label: "Instrument, sponge, and needle counts are correct", checked: true, required: true },
      { id: "c18", label: "Specimen labelling confirmed (Appendix - Patient P001 Arun Kumar)", checked: true, required: true },
      { id: "c19", label: "Whether there are any equipment problems to be addressed", checked: true, required: false },
      { id: "c20", label: "Surgeon, anesthesia, and nurse review key recovery and management concerns", checked: false, required: true },
      { id: "c21", label: "Post-operative PACU handoff report ready", checked: false, required: false },
      { id: "c22", label: "Post-op analgesia and anti-emetic prescription verified", checked: false, required: false },
      { id: "c23", label: "Patient warm and hemodynamically stable for transport", checked: false, required: true },
    ],
  },
];

export const suggestedPrompts = [
  { text: "Show me the patient details for P001", intent: "patient" },
  { text: "Show current vitals for patient P001", intent: "monitoring" },
  { text: "Show surgical checklist status", intent: "checklist" },
  { text: "Show me the MRI report for patient P001", intent: "rag" },
  { text: "What are the surgical precautions for laparoscopic appendectomy?", intent: "rag" },
  { text: "Check antibiotic timing and allergy alert", intent: "checklist" },
];
export const patientsData = {
  P001: patients[0],
  P002: patients[1],
  P003: patients[2],
};
export const whoChecklistData = surgicalChecklistData;
